### ISSUE TITLE
When i try to add the integration into Home assistant it succeeds but doesn't add any locks.

### ISSUE THREAD

**Issue by qbasasa** [rospogrigio/airbnk_mqtt#10]
Home assistant version: core-2021.12.1

When i try to add the lock it asks for the Mail and PIN and then said:
Success!
Created configuration for Airbnk..
But there were no popups to add the locks.

I have M531 Lock.

There is this error in the logs when i try to remove the integration:
2021-12-15 10:35:53 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Airbnk for airbnk_mqtt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 452, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/airbnk_mqtt/__init__.py", line 136, in async_unload_entry
    hass.data[DOMAIN].pop(config_entry.entry_id)
KeyError: 'ee22fc34c216a5beb6734fabcdf36259

**Comment by rospogrigio** [comment]
Have you installed the integration using HACS?
In any case we need more debug info, please enable debugging and send some logs.
To enable debugging, add the following lines to configuration.yaml:
`    custom_components.airbnk_mqtt: debug
    custom_components.airbnk_mqtt.config_flow: debug
    custom_components.airbnk_mqtt.custom_device: debug
    custom_components.airbnk_mqtt.tasmota_device: debug
    custom_components.airbnk_mqtt.cover: debug
    custom_components.airbnk_mqtt.sensor: debug
    custom_components.airbnk_mqtt.airbnk_api: debug
`
Bye...

**Comment by qbasasa** [comment]
I was wondering how to enable proper debugging, thank you!

Yes I've used hacs.
that's what i get after adding new integration:

`2021-12-15 17:21:35 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/config.py", line 938, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 129, in async_check_ha_config_file
    integration = await async_get_integration_with_requirements(hass, domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 58, in async_get_integration_with_requirements
    integration = await async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.sensor
2021-12-15 17:22:06 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/config.py", line 938, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 129, in async_check_ha_config_file
    integration = await async_get_integration_with_requirements(hass, domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 58, in async_get_integration_with_requirements
    integration = await async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.sensor
2021-12-15 17:22:44 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Airbnk for airbnk_mqtt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 452, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/airbnk_mqtt/__init__.py", line 136, in async_unload_entry
    hass.data[DOMAIN].pop(config_entry.entry_id)
KeyError: 'b8d514d332ae785fb1627560f54ed9fa'
2021-12-15 17:22:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140050754297232] Invalid domain custom_components.airbnk_mqtt.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 586, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 938, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 129, in async_check_ha_config_file
    integration = await async_get_integration_with_requirements(hass, domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 58, in async_get_integration_with_requirements
    integration = await async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.sensor`

**Comment by rospogrigio** [comment]
I don't know what's going on, maybe try to remove the integration and re-download it.
Also maybe provide some screenshot when you try to configure it...

**Comment by qbasasa** [comment]
When i don't touch a thing after startup i have this:
`2021-12-15 18:21:45 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration custom_components.airbnk_mqtt.cover - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 79, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 157, in _async_setup_component
    integration = await loader.async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.cover
2021-12-15 18:21:45 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration custom_components.airbnk_mqtt.airbnk_api - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 79, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 157, in _async_setup_component
    integration = await loader.async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.airbnk_api
2021-12-15 18:21:45 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration custom_components.airbnk_mqtt.tasmota_device - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 79, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 157, in _async_setup_component
    integration = await loader.async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.tasmota_device
2021-12-15 18:21:45 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration custom_components.airbnk_mqtt - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 79, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 157, in _async_setup_component
    integration = await loader.async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt
2021-12-15 18:21:45 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration custom_components.airbnk_mqtt.config_flow - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 79, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 157, in _async_setup_component
    integration = await loader.async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.config_flow
2021-12-15 18:21:45 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration custom_components.airbnk_mqtt.sensor - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 79, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 157, in _async_setup_component
    integration = await loader.async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.sensor
2021-12-15 18:21:45 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration custom_components.airbnk_mqtt.custom_device - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 79, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 157, in _async_setup_component
    integration = await loader.async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 580, in _async_get_integration
    raise ValueError(f"Invalid domain {domain}")
ValueError: Invalid domain custom_components.airbnk_mqtt.custom_device`

I will remove the folder and reinstall with HACS please wait

**Comment by qbasasa** [comment]
I tried also go downgrade and still the same issue, that's the message i get after imputing login and pin.
And then the integration appears in integrations but nothing happens.
![image](https://user-images.githubusercontent.com/55389998/146240943-bae8a94e-4c1b-4427-b86f-6c2fa6c4c21b.png)

**Comment by rospogrigio** [comment]
We need to enable debugging, are you sure you added the lines under the `logs:` section?
Another thing you might try is to remove the `not` you find in airbnk_api.py at line 122. Let me know if any of this works

**Comment by qbasasa** [comment]
This should make more sense, it looks there are no devices nut in phone app i have one.

`2021-12-15 19:20:57 INFO (MainThread) [custom_components.airbnk_mqtt.airbnk_api] Verification code request succeeded.
2021-12-15 19:21:26 INFO (MainThread) [custom_components.airbnk_mqtt.airbnk_api] Retrieving new Token...
2021-12-15 19:21:26 INFO (MainThread) [custom_components.airbnk_mqtt.airbnk_api] Retrieving: https://wehereapi.seamooncloud.com/api/lock/loginByAuthcode?loginAcct=mail@mail.mail&authCode=492477&systemCode=Android&language=2&version=A_FD_1.8.0&deviceID=123456789012345&mark=1
2021-12-15 19:21:27 INFO (MainThread) [custom_components.airbnk_mqtt.airbnk_api] Token retrieval succeeded.
2021-12-15 19:21:27 INFO (MainThread) [custom_components.airbnk_mqtt.config_flow] Token retrieval data: {'code': 200, 'data': {'unionId': '', 'gender': 0, 'phone': '', 'name': 'a********1@kermit.com.pl', 'pwd': '6766087E73BE098E017060720062F9D6', 'headPic': 'http://wehereapp.seamooncloud.com/img/logo.jpg', 'userId': 'cae37ac6-c989-4286-a4f2-a2ff263d34a3', 'markFirst': 0, 'email': 'airbnk2021@kermit.com.pl', 'token': 'c4b71c98-6889-4f88-a4ad-74a4b7f83893'}, 'info': 'OK', 'totalNum': 0, 'totalPage': 0}
2021-12-15 19:21:27 DEBUG (MainThread) [custom_components.airbnk_mqtt.config_flow] Done!: cae37ac6-c989-4286-a4f2-a2ff263d34a3 airbnk2021@kermit.com.pl c4b71c98-6889-4f88-a4ad-74a4b7f83893
2021-12-15 19:21:27 DEBUG (MainThread) [custom_components.airbnk_mqtt.airbnk_api] calling getCloudDevices()
2021-12-15 19:21:27 INFO (MainThread) [custom_components.airbnk_mqtt.airbnk_api] Retrieving: https://wehereapi.seamooncloud.com/api/v2/lock/getAllDevicesNew?language=2&userId=cae37ac6-c989-4286-a4f2-a2ff263d34a3&version=A_FD_1.8.0&token=c4b71c98-6889-4f88-a4ad-74a4b7f83893
2021-12-15 19:21:28 DEBUG (MainThread) [custom_components.airbnk_mqtt.airbnk_api] GetCloudDevices succeeded (200): {
	"code":200,
	"data":[
		{
			"sn":"-----",
			"deviceName":"name,
			"landlordId":"cae37ac6-c989-4286-a4f2-FFFFFFFFFF",
			"landlordName":"mail@mail",
			"groupId":"00000000-0000-0000-0000-000000000000",
			"permissions":"1,2,3,4,5",
			"addTime":1639553037055,
			"type":1,
			"deviceType":"M531",
			"clickTimes":6,
			"lastClickTime":1639561803711,
			"boardModel":"M531",
			"hardwareVersion":"13",
			"firmwareVersion":"1.1.0",
			"snInfo":"L1pamaVxgpGbUSYB3J70KjyZGfXOwD8kdkJLb+yKFeoRIOnzWX7M9LzekiH+DgnJ/wVZWV0KUqUdJT1oq9FR//8FWVldClKlHSU9aKvRUf//BVlZXQpSpR0lPWir0VH//wVZWV0KUqUdJT1oq9FR/9s6UHk/wTBP+R4L9U8jiyd430tmii7H6uCyMp1xqpNFdYWESNXqXE/w1q2S8hX+Kgrwp++6XTAcupECUJbt9NgQ4qZlVxTNm7OgQ8TBSIt71KxQfNH0iMUHJ0KRMwBVXlysgpW7Tzt+sl3GoX3zF6n/BVlZXQpSpR0lPWir0VH//wVZWV0KUqUdJT1oq9FR//8FWVldClKlHSU9aKvRUf//BVlZXQpSpR0lPWir0VH//wVZWV0KUqUdJT1oq9FR//8FWVldClKlHSU9aKvRUf//BVlZXQpSpR0lPWir0VH//wVZWV0KUqUdJT1oq9FR//8FWVldClKlHSU9aKvRUf//BVlZXQpSpR0lPWir0VH//wVZWV0KUqUdJT1oq9FR//8FWVldClKlHSU9aKvRUf//BVlZXQpSpR0lPWir0VH//wVZWV0KUqUdJT1oq9FR//8FWVldClKlHSU9aKvRUf//BVlZXQpSpR0lPWir0VH//wVZWV0KUqUdJT1oq9FR/+i/cVq1OcLiYGSr/pfPSVQ=065cee6cc02d341cb47d87b8f15629de",
			"sdkKey":"key1",
			"appKey":"key2",
			"newSninfo":"uOfEINWYYQ9H3/dZDi2hPxLBLYRnPQpF/1xT+FO8bdfXw4ZxfTudQc/VBqJG706goWhts6RlL0NCJutr67ufMzBUvk6JK+IPiL2HdZqEPScXSuz8iHYvXfBHZ7VNZreGTPfqWsiQrjBtyA==",
			"upgradeMark":0,
			"otpsninfo":"",
			"wifi":1,
			"gateway":"",
			"state":0,
			"fpic":"https://airbnk.51qd.org/pic/airbnk/appIcon/m531.png"
		}
	],
	"info":"OK",
	"totalNum":0,
	"totalPage":0
}
2021-12-15 19:21:28 INFO (MainThread) [custom_components.airbnk_mqtt.airbnk_api] Device 'Zamek górny' is filtered out
2021-12-15 19:21:28 INFO (MainThread) [homeassistant.setup] Setting up airbnk_mqtt
2021-12-15 19:21:28 INFO (MainThread) [homeassistant.setup] Setup of domain airbnk_mqtt took 0.0 seconds
2021-12-15 19:21:28 DEBUG (MainThread) [custom_components.airbnk_mqtt] DEVICES ARE {}
2021-12-15 19:21:28 INFO (MainThread) [homeassistant.components.cover] Setting up cover.airbnk_mqtt
2021-12-15 19:21:28 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.airbnk_mqtt`

**Comment by rospogrigio** [comment]
So is everything working now? Can we close the issue?

**Comment by qbasasa** [comment]
Sure, just curious is there a way to push a permanent fix for this?

**Comment by rospogrigio** [comment]
> Sure, just curious is there a way to push a permanent fix for this?

Of course, I'll do it soon!

**Comment by qbasasa** [comment]
Great,
I have another problem after i close the lock or open it it stays i this state and i cannot open it or close.
![image](https://user-images.githubusercontent.com/55389998/146252311-74acb7cb-bffc-441d-b1cc-08e395b19025.png)

**Comment by rospogrigio** [comment]
It takes some time to update the lock status. I suggest you try the custom firmware, it's much more responsive than Tasmota. We are still improving the status detection, however.

**Comment by qbasasa** [comment]
Got it, i need to setup everything in the INO file or it has some frontend to modify after flash?

**Comment by rospogrigio** [comment]
After you flash it, it will expose a Wifi connection: connect to it, and you can configure it from the url http://192.168.4.1.

**Comment by qbasasa** [comment]
Perfect, flashed !

**Comment by qbasasa** [comment]
If you need some help testing now that i know how to turn on debugging let me know and ill gladly help

**Comment by rospogrigio** [comment]
OK so now we published a new release of the integration and of the custom FW (1.0.4), please install them both and let us know how it goes. In my setup it is much more responsive, after you operate the lock it updates the status within 1-2 seconds.
Let me have your feedback, thank you!

**Comment by qbasasa** [comment]
Hi,
The status updates better, however the jammed status looks to be sticky.
Sometimes also still the commands don't open or close the lock, but i would need to test it for a longer period to see if it wasn't just a on off problem.
There is also something i noticed, i cannot update the firmware via webpage but it might be a problem with my esp32.

I have also switched the lock direction in cellphone app and in the integration closed status corresponds to open lock and the other way around, maybe it would be feasible to add system option to switch opened status with closed one?

**Comment by formatBCE** [comment]
> Hi,
> The status updates better, however the jammed status looks to be sticky.
> Sometimes also still the commands don't open or close the lock, but i would need to test it for a longer period to see if it wasn't just a on off problem.
> There is also something i noticed, i cannot update the firmware via webpage but it might be a problem with my esp32.
> 
> I have also switched the lock direction in cellphone app and in the integration closed status corresponds to open lock and the other way around, maybe it would be feasible to add system option to switch opened status with closed one?

On lock direction - maybe you can re-configure integration? There's definitely support for both directions in integration, but most probably it is set at initial configuration.

Try moving gateway closer to the lock, so your RSSI would be around -60 - -75. It helps a lot to stabilize.

On OTA: what is behavior there?
Does it show percentage and freeze before 100?
If so, does it freeze on particular percent?
If yes, then there might be not enough room for new firmware to cache it...
If doesn't freeze, but after reboot there's still old software, it  may indicate some problems with chip flash... 
Anyway, serial logs would help a lot :)

**Comment by qbasasa** [comment]
Ill get the logs tomorrow!
The ota stops at 9% and nothing happens it doesn't work but it also doesn't break the old version so flash probably didn't even start, im a bit afraid to look into the logs maybe they say exacly whats wrong!

For the direction it was set up before i integrated it into hass i will try to re add the lock tomorrow but its not an issue at all :)

Now the lock is closer!
![image](https://user-images.githubusercontent.com/55389998/146468856-c3b4d8f4-6b0b-4373-82fd-e172d52be1ca.png)

**Comment by formatBCE** [comment]
RSSI -82 is still pretty low. But enough, I guess.
OTA doesn't overwrite existing firmware. Instead there are two different areas for firmware on device. When OTA happens, it writes to non-active partition, and then moves boot flag to it, and reboots.
Fail-safe. :)
But I guess in your case flash side is too small for two partitions (plus partition for raw uploaded firmware), so it cannot perform OTA. Sorry to hear.
Hmm, with lock direction I guess @rospogrigio can help.

**Comment by qbasasa** [comment]
Didn't have yet time to check but sometimes the lock isnt responding to commands.
Also weird thing the esp32 reseted itself to factory settings with the default wifi configuration network available :)

I will check reflashing when will get to fixing that.

**Comment by formatBCE** [comment]
> Didn't have yet time to check but sometimes the lock isnt responding to commands.
> Also weird thing the esp32 reseted itself to factory settings with the default wifi configuration network available :)
> 
> I will check reflashing when will get to fixing that.

Yes, there was a mechanism to reset config on ESP, if WiFi is inaccessible for some time.
We removed it in gateway firmware version 1.0.6.

**Comment by qbasasa** [comment]
Ive updates the esp32 and changed the partition a bit, when next update arrives i will let you know how it went.

Also re added lock and still open/close status is switched. But closing opening works even thou it some time doesnt respond, ive moved ESP closer to the lock once more now its around 1m from it.

17 Dec 2021 21:10:54 formatBCE ***@***.***>:

**Comment by formatBCE** [comment]
@qbasasa just make sure you don't spam lock with commands - it doesn't like it and can become unresponsive :)
On OTA - you can try updating with same version, it still does write it.

**Comment by qbasasa** [comment]
OK will do, also noticed something weird after 12h the custom esp32 firmware deassigned from dhcp on my mikrotik(twice), maybe an option for static ip in the config could fix that or announcing DHCP from time to time, unless there something else happening.
I've changed the lease time to 4 days for now to check if it's the router at fault :)

**Comment by formatBCE** [comment]
> OK will do, also noticed something weird after 12h the custom esp32 firmware deassigned from dhcp on my mikrotik(twice), maybe an option for static ip in the config could fix that or announcing DHCP from time to time, unless there something else happening.
> I've changed the lease time to 4 days for now to check if it's the router at fault :)
> 
> 
> PS.
> After changing the partition table on ESP32 the updater works fine for 1.0.6, so it was all my fault...

You're reporting more and more weird issues. :)
For me, devise is stable and reliable.
Don't even imagine, what can lead to DHCP problem.

**Comment by qbasasa** [comment]
Maybe my ESP is a piece of trash, it was in my drawer for a long time.

18 Dec 2021 18:18:34 formatBCE ***@***.***>:

**Comment by qbasasa** [comment]
I've picked another esp32... i think this one have problems with stability..
